CREATE TABLE R_CONTINENTES (
  ID_CONTINENTE INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NOME_CONTINENTE_PORTUGUES VARCHAR(255) NOT NULL,
  NOME_CONTINENTE_INGLES VARCHAR(255) NOT NULL
);
COMMENT ON TABLE R_CONTINENTES IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';