CREATE TABLE R_PAISES (
  ID_PAIS INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ID_CONTINENTE INTEGER NOT NULL,
  NOME_PAIS_PORTUGUES VARCHAR(255) NOT NULL,
  NOME_PAIS_INGLES VARCHAR(255) NOT NULL,
  FOREIGN KEY (ID_CONTINENTE) REFERENCES R_CONTINENTES(ID_CONTINENTE)
);
COMMENT ON TABLE R_PAISES IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';