CREATE TABLE R_PAISES_APELIDOS_TIPOS (
    ID_TIPO_APELIDO INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TIPO_APELIDO VARCHAR(255) NOT NULL
);
COMMENT ON TABLE R_PAISES_APELIDOS_TIPOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';