CREATE TABLE R_PAISES_APELIDOS (
  ID_APELIDO_PAIS INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ID_TIPO_APELIDO INTEGER NOT NULL,
  APELIDO VARCHAR(255) NOT NULL,
  ID_PAIS INTEGER NOT NULL,
  FOREIGN KEY (ID_TIPO_APELIDO) REFERENCES R_PAISES_APELIDOS_TIPOS(ID_TIPO_APELIDO),
  FOREIGN KEY (ID_PAIS) REFERENCES R_PAISES(ID_PAIS)
);
COMMENT ON TABLE R_PAISES_APELIDOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';