CREATE TABLE R_GRUPOS_GEOPOLITICOS (
  ID_GRUPO_GEOPOLITICO INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NOME_GRUPO_PORTUGUES VARCHAR(255) NOT NULL,
  NOME_GRUPO_INGLES VARCHAR(255) NOT NULL,
  SIGLA VARCHAR(255) DEFAULT NULL
);
COMMENT ON TABLE R_GRUPOS_GEOPOLITICOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';