CREATE TABLE R_PAISES_PARA_GRUPOS_GEOPOLITICOS (
  ID_GRUPO_GEOPOLITICO INTEGER NOT NULL,
  ID_PAIS INTEGER NOT NULL,
  PRIMARY KEY (ID_GRUPO_GEOPOLITICO, ID_PAIS),
  FOREIGN KEY (ID_GRUPO_GEOPOLITICO) REFERENCES R_GRUPOS_GEOPOLITICOS (ID_GRUPO_GEOPOLITICO),
  FOREIGN KEY (ID_PAIS) REFERENCES R_PAISES(ID_PAIS)
);
COMMENT ON TABLE R_PAISES_PARA_GRUPOS_GEOPOLITICOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';