CREATE TABLE R_UNIVERSIDADES (
  ID_UNIVERSIDADE INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COD_IES INTEGER DEFAULT NULL, -- para universidades brasileiras se ligarem à tabela IES
  NOME_UNIVERSIDADE_PORTUGUES VARCHAR(2048) NOT NULL,
  NOME_UNIVERSIDADE_INGLES VARCHAR(2048) NOT NULL,
  SIGLA VARCHAR(255) DEFAULT NULL,
  ID_APELIDO_PAIS INTEGER NOT NULL,
  FOREIGN KEY (ID_APELIDO_PAIS) REFERENCES R_PAISES_APELIDOS(ID_APELIDO_PAIS)
);
COMMENT ON TABLE R_UNIVERSIDADES IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';