CREATE TABLE R_UNIVERSIDADES_APELIDOS (
  ID_APELIDO_UNIVERSIDADE INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ID_UNIVERSIDADE INTEGER NOT NULL,
  APELIDO VARCHAR(2048) NOT NULL,
  FOREIGN KEY (ID_UNIVERSIDADE) REFERENCES R_UNIVERSIDADES(ID_UNIVERSIDADE)
);
COMMENT ON TABLE R_UNIVERSIDADES_APELIDOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';