CREATE TABLE R_RANKINGS (
    ID_RANKING INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NOME_RANKING VARCHAR(255) UNIQUE NOT NULL,
    NOME_CURTO_PORTUGUES VARCHAR(255) DEFAULT NULL,
    NOME_CURTO_INGLES VARCHAR(255) DEFAULT NULL,
    ABRANGENCIA_PORTUGUES VARCHAR(255) DEFAULT NULL,
    ABRANGENCIA_INGLES VARCHAR(255) DEFAULT NULL,
    DESCRICAO_PORTUGUES VARCHAR(255) DEFAULT NULL,
    DESCRICAO_INGLES VARCHAR(255) DEFAULT NULL,
    ORDEM_EXIBICAO INTEGER DEFAULT NULL,
    EXIBIR BOOLEAN DEFAULT TRUE,
    ULTIMA_ATUALIZACAO TIMESTAMP(6) DEFAULT NULL
);
COMMENT ON TABLE R_RANKINGS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';