CREATE TABLE R_PILARES (
  ID_PILAR INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ID_RANKING INTEGER NOT NULL,
  NOME_PILAR_PORTUGUES VARCHAR(255) NOT NULL,
  NOME_PILAR_INGLES VARCHAR(255) NOT NULL,
  DESCRICAO_PILAR_PORTUGUES VARCHAR(255) DEFAULT NULL,
  DESCRICAO_PILAR_INGLES VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (ID_RANKING) REFERENCES R_RANKINGS(ID_RANKING)
);
COMMENT ON TABLE R_PILARES IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';