CREATE TABLE R_PILARES_DETALHES (
  ID_PILAR_DETALHE INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ID_PILAR INTEGER NOT NULL,
  ANO_REFERENCIA  SMALLINT,
  IDENTIFICADOR CHAR(5) NOT NULL,
  DESCRICAO_CRITERIO_INGLES VARCHAR(255) NOT NULL,
  DESCRICAO_CRITERIO_PORTUGUES VARCHAR(255),
  PONTUACAO	SMALLINT NOT NULL,
  PONTUACAO_MAXIMA SMALLINT,
  FOREIGN KEY (ID_PILAR) REFERENCES R_PILARES(ID_PILAR)
);
COMMENT ON TABLE R_PILARES_DETALHES IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';