CREATE TABLE R_PILARES_GRUPOS (
  ID_GRUPO_PILARES INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NOME_GRUPO_PORTUGUES VARCHAR(255) NOT NULL,
  NOME_GRUPO_INGLES VARCHAR(255) NOT NULL
);
COMMENT ON TABLE R_PILARES_GRUPOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';