CREATE TABLE R_PILARES_PARA_GRUPOS (
  ID_PILAR INTEGER NOT NULL,
  ID_GRUPO_PILARES INTEGER NOT NULL,
  PRIMARY KEY (ID_PILAR, ID_GRUPO_PILARES),
  FOREIGN KEY (ID_PILAR) REFERENCES R_PILARES(ID_PILAR),
  FOREIGN KEY (ID_GRUPO_PILARES) REFERENCES R_PILARES_GRUPOS(ID_GRUPO_PILARES)
);
COMMENT ON TABLE R_PILARES_PARA_GRUPOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';