-- continentes, países, subdivisões de países e grupos geopolíticos

CREATE TABLE R_CONTINENTES (
  ID_CONTINENTE INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NOME_CONTINENTE_PORTUGUES VARCHAR(255) NOT NULL,
  NOME_CONTINENTE_INGLES VARCHAR(255) NOT NULL
);
COMMENT ON TABLE R_CONTINENTES IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

CREATE TABLE R_PAISES (
  ID_PAIS INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ID_CONTINENTE INTEGER NOT NULL,
  NOME_PAIS_PORTUGUES VARCHAR(255) NOT NULL,
  NOME_PAIS_INGLES VARCHAR(255) NOT NULL,
  FOREIGN KEY (ID_CONTINENTE) REFERENCES R_CONTINENTES(ID_CONTINENTE)
);
COMMENT ON TABLE R_PAISES IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

CREATE TABLE R_PAISES_APELIDOS_TIPOS (
    ID_TIPO_APELIDO INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TIPO_APELIDO VARCHAR(255) NOT NULL
);
COMMENT ON TABLE R_PAISES_APELIDOS_TIPOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

CREATE TABLE R_PAISES_APELIDOS (
  ID_APELIDO_PAIS INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ID_TIPO_APELIDO INTEGER NOT NULL,
  APELIDO VARCHAR(255) NOT NULL,
  ID_PAIS INTEGER NOT NULL,
  FOREIGN KEY (ID_TIPO_APELIDO) REFERENCES R_PAISES_APELIDOS_TIPOS(ID_TIPO_APELIDO),
  FOREIGN KEY (ID_PAIS) REFERENCES R_PAISES(ID_PAIS)
);
COMMENT ON TABLE R_PAISES_APELIDOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

CREATE TABLE R_GRUPOS_GEOPOLITICOS (
  ID_GRUPO_GEOPOLITICO INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NOME_GRUPO_PORTUGUES VARCHAR(255) NOT NULL,
  NOME_GRUPO_INGLES VARCHAR(255) NOT NULL,
  SIGLA VARCHAR(255) DEFAULT NULL
);
COMMENT ON TABLE R_GRUPOS_GEOPOLITICOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

CREATE TABLE R_PAISES_PARA_GRUPOS_GEOPOLITICOS (
  ID_GRUPO_GEOPOLITICO INTEGER NOT NULL,
  ID_PAIS INTEGER NOT NULL,
  PRIMARY KEY (ID_GRUPO_GEOPOLITICO, ID_PAIS),
  FOREIGN KEY (ID_GRUPO_GEOPOLITICO) REFERENCES R_GRUPOS_GEOPOLITICOS (ID_GRUPO_GEOPOLITICO),
  FOREIGN KEY (ID_PAIS) REFERENCES R_PAISES(ID_PAIS)
);
COMMENT ON TABLE R_PAISES_PARA_GRUPOS_GEOPOLITICOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

-- universidades e seus grupos

CREATE TABLE R_UNIVERSIDADES (
  ID_UNIVERSIDADE INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COD_IES INTEGER DEFAULT NULL, -- para universidades brasileiras se ligarem à tabela IES
  NOME_UNIVERSIDADE_PORTUGUES VARCHAR(2048) NOT NULL,
  NOME_UNIVERSIDADE_INGLES VARCHAR(2048) NOT NULL,
  SIGLA VARCHAR(255) DEFAULT NULL,
  ID_APELIDO_PAIS INTEGER NOT NULL,
  FOREIGN KEY (ID_APELIDO_PAIS) REFERENCES R_PAISES_APELIDOS(ID_APELIDO_PAIS)
);
COMMENT ON TABLE R_UNIVERSIDADES IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

CREATE TABLE R_UNIVERSIDADES_APELIDOS (
  ID_APELIDO_UNIVERSIDADE INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ID_UNIVERSIDADE INTEGER NOT NULL,
  APELIDO VARCHAR(2048) NOT NULL,
  FOREIGN KEY (ID_UNIVERSIDADE) REFERENCES R_UNIVERSIDADES(ID_UNIVERSIDADE)
);
COMMENT ON TABLE R_UNIVERSIDADES_APELIDOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

CREATE TABLE R_UNIVERSIDADES_GRUPOS (
  ID_GRUPO_UNIVERSIDADES INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NOME_GRUPO_PORTUGUES VARCHAR(255) NOT NULL,
  NOME_GRUPO_INGLES VARCHAR(255) NOT NULL
);
COMMENT ON TABLE R_UNIVERSIDADES_GRUPOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

CREATE TABLE R_UNIVERSIDADES_PARA_GRUPOS (
  ID_UNIVERSIDADE INTEGER NOT NULL,
  ID_GRUPO_UNIVERSIDADES INTEGER NOT NULL,
  PRIMARY KEY (ID_UNIVERSIDADE, ID_GRUPO_UNIVERSIDADES),
  FOREIGN KEY (ID_UNIVERSIDADE) REFERENCES R_UNIVERSIDADES(ID_UNIVERSIDADE),
  FOREIGN KEY (ID_GRUPO_UNIVERSIDADES) REFERENCES R_UNIVERSIDADES_GRUPOS(ID_GRUPO_UNIVERSIDADES)
);
COMMENT ON TABLE R_UNIVERSIDADES_PARA_GRUPOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

-- rankings e métricas

CREATE TABLE R_RANKINGS (
    ID_RANKING INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NOME_RANKING VARCHAR(255) UNIQUE NOT NULL,
    ULTIMA_ATUALIZACAO TIMESTAMP(6) DEFAULT NULL
);
COMMENT ON TABLE R_RANKINGS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

CREATE TABLE R_PILARES (
  ID_PILAR INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ID_RANKING INTEGER NOT NULL,
  NOME_PILAR_PORTUGUES VARCHAR(255) NOT NULL,
  NOME_PILAR_INGLES VARCHAR(255) NOT NULL,
  DESCRICAO_PILAR_PORTUGUES VARCHAR(255) DEFAULT NULL,
  DESCRICAO_PILAR_INGLES VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (ID_RANKING) REFERENCES R_RANKINGS(ID_RANKING)
);
COMMENT ON TABLE R_PILARES IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

CREATE TABLE R_PILARES_DETALHES (
  ID_PILAR_DETALHE INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ID_PILAR INTEGER NOT NULL,
  ANO_REFERENCIA  SMALLINT,
  IDENTIFICADOR CHAR(5) NOT NULL,
  DESCRICAO_CRITERIO_INGLES VARCHAR(255) NOT NULL,
  DESCRICAO_CRITERIO_PORTUGUES VARCHAR(255),
  PONTUACAO	SMALLINT NOT NULL,
  PONTUACAO_MAXIMA SMALLINT,
  FOREIGN KEY (ID_PILAR) REFERENCES R_PILARES(ID_PILAR)
);
COMMENT ON TABLE R_PILARES_DETALHES IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

CREATE TABLE R_PILARES_GRUPOS (
  ID_GRUPO_PILARES INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NOME_GRUPO_PORTUGUES VARCHAR(255) NOT NULL,
  NOME_GRUPO_INGLES VARCHAR(255) NOT NULL
);
COMMENT ON TABLE R_PILARES_GRUPOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

CREATE TABLE R_PILARES_PARA_GRUPOS (
  ID_PILAR INTEGER NOT NULL,
  ID_GRUPO_PILARES INTEGER NOT NULL,
  PRIMARY KEY (ID_PILAR, ID_GRUPO_PILARES),
  FOREIGN KEY (ID_PILAR) REFERENCES R_PILARES(ID_PILAR),
  FOREIGN KEY (ID_GRUPO_PILARES) REFERENCES R_PILARES_GRUPOS(ID_GRUPO_PILARES)
);
COMMENT ON TABLE R_PILARES_PARA_GRUPOS IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

CREATE TABLE R_PILARES_VALORES (
  ID_APELIDO_UNIVERSIDADE INTEGER NOT NULL,
  ID_PILAR INTEGER NOT NULL,
  ANO INTEGER NOT NULL,
  VALOR_INICIAL REAL DEFAULT NULL,  -- valor final do intervalo caso o pilar possua um intervalo de valores
  VALOR_FINAL REAL DEFAULT NULL,  -- valor final do intervalo caso o pilar possua um intervalo de valores
  PRIMARY KEY (ID_APELIDO_UNIVERSIDADE, ID_PILAR, ANO),
  FOREIGN KEY (ID_APELIDO_UNIVERSIDADE) REFERENCES R_UNIVERSIDADES_APELIDOS(ID_APELIDO_UNIVERSIDADE),
  FOREIGN KEY (ID_PILAR) REFERENCES R_PILARES(ID_PILAR)
);
COMMENT ON TABLE R_PILARES_VALORES IS 'Parte do conjunto de tabelas da aplicação Rankings. Para mais informações, consulte https://github.com/COPLIN-UFSM/rankings';

