name: rankings
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.*
  - pip
  - pandas=2.*
  - beautifulsoup4
  - tqdm
  - requests=2.*
  - selenium
  - urllib3==1.26.*
  - jinja2
  - pip:
      - ibm_db_django
      - django-nested-inline
      - django==5.2.*
      - django-bootstrap5
      - django-crispy-forms
      - crispy-bootstrap5
      - django-contrib-comments
      - sqlparse
      - sentence-transformers
      - pytest
