name: rankings
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.11.*
  - pandas=2.*
  - beautifulsoup4
  - pytorch
  - scikit-learn
  - scipy
  - tqdm
  - requests=2.*
  - selenium
  - urllib3==1.26.*
  - pip:
      - ibm_db
      - coplin-db2
      - ibm-db-django
      - wakepy
      - django-nested-inline
      - django==5.2.*
      - django-bootstrap-v5
      - django-crispy-forms
      - crispy-bootstrap5
      - django-contrib-comments
      - sqlparse
      - sentence-transformers
      - huggingface
      - transformers
      - pytest