name: rankings
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.*
  - pip
  - pandas=2.*
  - beautifulsoup4
  - tqdm
  - numpy
  - matplotlib=3.*
  - requests=2.*
  - selenium
  - urllib3==1.26.*
  - jinja2
  - pip:
      - coplin-db2==2.*
      - dash-bootstrap-components==1.5.*
      - wakepy
      - django-nested-inline
      - django==5.2.*
      - django-bootstrap5
      - django-contrib-comments
      - django-crispy-forms
      - crispy-bootstrap5
      - ibm-db-django
      - sqlparse
      - openpyxl
      - ftfy
      - pytest
      - sentence-transformers
