-- tabelas inseridas pelo django
DROP TABLE IF EXISTS auth_group_permissions;
DROP TABLE IF EXISTS auth_user_groups;
DROP TABLE IF EXISTS auth_group;
DROP TABLE IF EXISTS auth_user_user_permissions;
DROP TABLE IF EXISTS auth_permission;
DROP TABLE IF EXISTS django_admin_log;
DROP TABLE IF EXISTS auth_user;
DROP TABLE IF EXISTS django_content_type;
DROP TABLE IF EXISTS django_migrations;
DROP TABLE IF EXISTS django_session;

-- tabelas do banco de dados de rankings
DROP TABLE IF EXISTS R_FORMULARIOS;
DROP TABLE IF EXISTS R_METADADOS;
DROP TABLE IF EXISTS R_METRICAS_PARA_PILARES;
DROP TABLE IF EXISTS R_METRICAS_VALORES;
DROP TABLE IF EXISTS R_METRICAS;
DROP TABLE IF EXISTS R_PAISES_PARA_GRUPOS_GEOPOLITICOS;
DROP TABLE IF EXISTS R_GRUPOS_GEOPOLITICOS;
DROP TABLE IF EXISTS R_PILARES_PARA_GRUPOS;
DROP TABLE IF EXISTS R_PILARES_GRUPOS;
DROP TABLE IF EXISTS R_PILARES_VALORES;
DROP TABLE IF EXISTS R_PILARES;
DROP TABLE IF EXISTS R_PILARES_DETALHES;
DROP TABLE IF EXISTS R_RANKINGS;
DROP TABLE IF EXISTS R_TIPOS_ENTIDADES;
DROP TABLE IF EXISTS R_TIPOS_METADADOS;
DROP TABLE IF EXISTS R_UNIVERSIDADES_APELIDOS;
DROP TABLE IF EXISTS R_UNIVERSIDADES_PARA_GRUPOS;
DROP TABLE IF EXISTS R_UNIVERSIDADES;
DROP TABLE IF EXISTS R_PAISES_APELIDOS;
DROP TABLE IF EXISTS R_PAISES;
DROP TABLE IF EXISTS R_CONTINENTES;
DROP TABLE IF EXISTS R_PAISES_APELIDOS_TIPOS;
DROP TABLE IF EXISTS R_UNIVERSIDADES_GRUPOS;

-- views
DROP VIEW R_V_RANKINGS_DIMENSAO;
DROP VIEW R_V_UNIVERSIDADES_DIMENSAO;
DROP VIEW R_V_PILARES_VALORES_FATO;