# Generated by Django 4.1 on 2023-10-18 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApelidoDePais",
            fields=[
                (
                    "id_apelido",
                    models.AutoField(
                        db_column="ID_APELIDO_PAIS", primary_key=True, serialize=False
                    ),
                ),
                (
                    "apelido",
                    models.CharField(
                        db_column="APELIDO", max_length=200, verbose_name="Apelido"
                    ),
                ),
            ],
            options={
                "verbose_name": "Apelido",
                "verbose_name_plural": "Apelidos",
                "db_table": "R_PAISES_APELIDOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ApelidoDeUniversidade",
            fields=[
                (
                    "id_apelido",
                    models.AutoField(
                        db_column="ID_APELIDO_UNIVERSIDADE",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "apelido",
                    models.CharField(
                        blank=True,
                        db_column="APELIDO",
                        max_length=200,
                        null=True,
                        verbose_name="Apelido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apelido",
                "verbose_name_plural": "Apelidos",
                "db_table": "R_UNIVERSIDADES_APELIDOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Continente",
            fields=[
                (
                    "id_continente",
                    models.AutoField(
                        db_column="ID_CONTINENTE", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nome_portugues",
                    models.CharField(
                        db_column="NOME_CONTINENTE_PORTUGUES",
                        max_length=200,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    models.CharField(
                        blank=True,
                        db_column="NOME_CONTINENTE_INGLES",
                        max_length=200,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
            ],
            options={
                "db_table": "R_CONTINENTES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Formulario",
            fields=[
                (
                    "id_formulario",
                    models.AutoField(
                        db_column="ID_FORMULARIO", primary_key=True, serialize=False
                    ),
                ),
                (
                    "data",
                    models.DateTimeField(
                        blank=True,
                        db_column="DATA",
                        default=django.utils.timezone.now,
                        verbose_name="Data",
                    ),
                ),
                (
                    "formulario",
                    models.FileField(
                        db_column="FORMULARIO",
                        upload_to="uploads",
                        verbose_name="Arquivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulário",
                "verbose_name_plural": "Formulários",
                "db_table": "R_FORMULARIOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GrupoDePilares",
            fields=[
                (
                    "id_grupo_pilares",
                    models.AutoField(
                        db_column="ID_GRUPO_PILARES", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nome_portugues",
                    models.CharField(
                        db_column="NOME_GRUPO_PORTUGUES",
                        max_length=200,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    models.CharField(
                        blank=True,
                        db_column="NOME_GRUPO_INGLES",
                        max_length=200,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de pilares",
                "verbose_name_plural": "Grupos de Pilares",
                "db_table": "R_PILARES_GRUPOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GrupoDeUniversidades",
            fields=[
                (
                    "id_grupo_universidades",
                    models.AutoField(
                        db_column="ID_GRUPO_UNIVERSIDADES",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome_portugues",
                    models.CharField(
                        db_column="NOME_GRUPO_PORTUGUES",
                        max_length=200,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    models.CharField(
                        blank=True,
                        db_column="NOME_GRUPO_INGLES",
                        max_length=200,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Universidades",
                "verbose_name_plural": "Grupos de Universidades",
                "db_table": "R_UNIVERSIDADES_GRUPOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GrupoGeopolitico",
            fields=[
                (
                    "id_grupo_geopolitico",
                    models.AutoField(
                        db_column="ID_GRUPO_GEOPOLITICO",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome_portugues",
                    models.CharField(
                        db_column="NOME_GRUPO_PORTUGUES",
                        max_length=200,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    models.CharField(
                        blank=True,
                        db_column="NOME_GRUPO_INGLES",
                        max_length=200,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
                (
                    "sigla",
                    models.CharField(
                        blank=True,
                        db_column="SIGLA",
                        max_length=200,
                        null=True,
                        verbose_name="Sigla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo geopolítico",
                "verbose_name_plural": "Grupos Geopolíticos",
                "db_table": "R_GRUPOS_GEOPOLITICOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Metadado",
            fields=[
                (
                    "id_metadado",
                    models.AutoField(
                        db_column="ID_METADADO", primary_key=True, serialize=False
                    ),
                ),
                (
                    "id_entidade",
                    models.IntegerField(blank=True, db_column="ID_ENTIDADE", null=True),
                ),
                ("ano", models.IntegerField(db_column="ANO")),
                ("valor", models.TextField(db_column="VALOR")),
            ],
            options={
                "db_table": "R_METADADOS",
                "ordering": ["-ano", "tipo_entidade", "tipo_metadado"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Metrica",
            fields=[
                (
                    "id_metrica",
                    models.AutoField(
                        db_column="ID_METRICA", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nome_portugues",
                    models.CharField(
                        db_column="NOME_METRICA_PORTUGUES",
                        max_length=200,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    models.CharField(
                        blank=True,
                        db_column="NOME_METRICA_INGLES",
                        max_length=200,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrica",
                "verbose_name_plural": "Métricas",
                "db_table": "R_METRICAS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id_pais",
                    models.AutoField(
                        db_column="ID_PAIS",
                        primary_key=True,
                        serialize=False,
                        verbose_name="País",
                    ),
                ),
                (
                    "nome_portugues",
                    models.CharField(
                        db_column="NOME_PAIS_PORTUGUES",
                        max_length=200,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    models.CharField(
                        blank=True,
                        db_column="NOME_PAIS_INGLES",
                        max_length=200,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
            ],
            options={
                "verbose_name": "País",
                "verbose_name_plural": "Países",
                "db_table": "R_PAISES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pilar",
            fields=[
                (
                    "id_pilar",
                    models.AutoField(
                        db_column="ID_PILAR", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nome_portugues",
                    models.CharField(
                        db_column="NOME_PILAR_PORTUGUES",
                        max_length=200,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    models.CharField(
                        blank=True,
                        db_column="NOME_PILAR_INGLES",
                        max_length=200,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
                (
                    "descricao_portugues",
                    models.CharField(
                        blank=True,
                        db_column="DESCRICAO_PILAR_PORTUGUES",
                        max_length=200,
                        null=True,
                        verbose_name="Descrição (PT-BR)",
                    ),
                ),
                (
                    "descricao_ingles",
                    models.CharField(
                        blank=True,
                        db_column="DESCRICAO_PILAR_INGLES",
                        max_length=200,
                        null=True,
                        verbose_name="Descrição (EN-US)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pilar",
                "verbose_name_plural": "Pilares",
                "db_table": "R_PILARES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id_ranking",
                    models.AutoField(
                        db_column="ID_RANKING", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        db_column="NOME_RANKING",
                        max_length=200,
                        unique=True,
                        verbose_name="Nome",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ranking",
                "verbose_name_plural": "Rankings",
                "db_table": "R_RANKINGS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoApelido",
            fields=[
                (
                    "id_tipo_apelido",
                    models.AutoField(
                        db_column="ID_TIPO_APELIDO", primary_key=True, serialize=False
                    ),
                ),
                (
                    "tipo_apelido",
                    models.CharField(
                        db_column="TIPO_APELIDO",
                        max_length=200,
                        verbose_name="Tipo Apelido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo Apelido",
                "verbose_name_plural": "Tipos Apelidos",
                "db_table": "R_PAISES_APELIDOS_TIPOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoDeEntidade",
            fields=[
                (
                    "id_tipo_entidade",
                    models.AutoField(
                        db_column="ID_TIPO_ENTIDADE", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.TextField(db_column="NOME_TIPO_ENTIDADE")),
            ],
            options={
                "verbose_name": "Tipo de Entidade",
                "verbose_name_plural": "Tipos de Entidades",
                "db_table": "R_TIPOS_ENTIDADES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoDeMetadado",
            fields=[
                (
                    "id_tipo_metadado",
                    models.AutoField(
                        db_column="ID_TIPO_METADADO", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.TextField(db_column="NOME_TIPO_METADADO")),
            ],
            options={
                "verbose_name": "Tipo de Metadado",
                "verbose_name_plural": "Tipos de Metadados",
                "db_table": "R_TIPOS_METADADOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Universidade",
            fields=[
                (
                    "id_universidade",
                    models.AutoField(
                        db_column="ID_UNIVERSIDADE", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nome_portugues",
                    models.CharField(
                        db_column="NOME_UNIVERSIDADE_PORTUGUES",
                        max_length=200,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    models.CharField(
                        blank=True,
                        db_column="NOME_UNIVERSIDADE_INGLES",
                        max_length=200,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
                (
                    "sigla",
                    models.CharField(
                        blank=True,
                        db_column="SIGLA",
                        max_length=200,
                        null=True,
                        verbose_name="Sigla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Universidade",
                "verbose_name_plural": "Universidades",
                "db_table": "R_UNIVERSIDADES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MetricasParaPilares",
            fields=[
                (
                    "metrica",
                    models.OneToOneField(
                        db_column="ID_METRICA",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="rankings.metrica",
                        verbose_name="Métrica",
                    ),
                ),
                (
                    "peso",
                    models.FloatField(
                        db_column="PESO",
                        default=1,
                        verbose_name="Ponderação da métrica no pilar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor da Métrica",
                "verbose_name_plural": "Valores das Métricas",
                "db_table": "R_METRICAS_PARA_PILARES",
                "ordering": ["metrica", "pilar"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MetricaValor",
            fields=[
                (
                    "metrica",
                    models.OneToOneField(
                        db_column="ID_METRICA",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="rankings.metrica",
                        verbose_name="Métrica",
                    ),
                ),
                ("ano", models.IntegerField(blank=True, db_column="ANO")),
                (
                    "valor_inicial",
                    models.FloatField(
                        blank=True,
                        db_column="VALOR_INICIAL",
                        null=True,
                        verbose_name="Valor inicial intervalo",
                    ),
                ),
                (
                    "valor_final",
                    models.FloatField(
                        blank=True,
                        db_column="VALOR_FINAL",
                        null=True,
                        verbose_name="Valor final intervalo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor da Métrica",
                "verbose_name_plural": "Valores das Métricas",
                "db_table": "R_METRICAS_VALORES",
                "ordering": ["-ano", "apelido_universidade", "metrica"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PaisesParaGruposGeopoliticos",
            fields=[
                (
                    "grupo_geopolitico",
                    models.OneToOneField(
                        blank=True,
                        db_column="ID_GRUPO_GEOPOLITICO",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="rankings.grupogeopolitico",
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
            ],
            options={
                "db_table": "R_PAISES_PARA_GRUPOS_GEOPOLITICOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PilaresParaGrupos",
            fields=[
                (
                    "pilar",
                    models.OneToOneField(
                        db_column="ID_PILAR",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="rankings.pilar",
                        verbose_name="Pilar",
                    ),
                ),
            ],
            options={
                "db_table": "R_PILARES_PARA_GRUPOS",
                "ordering": ["grupo_pilares", "pilar"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PilarValor",
            fields=[
                (
                    "apelido_universidade",
                    models.OneToOneField(
                        db_column="ID_APELIDO_UNIVERSIDADE",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="rankings.apelidodeuniversidade",
                    ),
                ),
                ("ano", models.IntegerField(db_column="ANO", verbose_name="Ano")),
                (
                    "valor_inicial",
                    models.FloatField(
                        blank=True,
                        db_column="VALOR_INICIAL",
                        null=True,
                        verbose_name="Valor Inicial",
                    ),
                ),
                (
                    "valor_final",
                    models.FloatField(
                        blank=True,
                        db_column="VALOR_FINAL",
                        null=True,
                        verbose_name="Valor Final",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor do Pilar",
                "verbose_name_plural": "Valores dos Pilares",
                "db_table": "R_PILARES_VALORES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UniversidadesParaGrupos",
            fields=[
                (
                    "universidade",
                    models.OneToOneField(
                        db_column="ID_UNIVERSIDADE",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="rankings.universidade",
                        verbose_name="Universidade",
                    ),
                ),
            ],
            options={
                "db_table": "R_UNIVERSIDADES_PARA_GRUPOS",
                "managed": False,
            },
        ),
    ]
