# Generated by Django 5.2.5 on 2025-10-15 09:56

import django.utils.timezone
import rankings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApelidoDePais",
            fields=[
                (
                    "id_apelido",
                    models.AutoField(
                        db_column="ID_APELIDO_PAIS", primary_key=True, serialize=False
                    ),
                ),
                (
                    "apelido",
                    rankings.models.UnicodeEscapedCharField(
                        db_column="APELIDO", max_length=512, verbose_name="Apelido"
                    ),
                ),
            ],
            options={
                "verbose_name": "Apelido",
                "verbose_name_plural": "Apelidos",
                "db_table": "R_PAISES_APELIDOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ApelidoDeUniversidade",
            fields=[
                (
                    "id_apelido",
                    models.AutoField(
                        db_column="ID_APELIDO_UNIVERSIDADE",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "apelido",
                    rankings.models.UnicodeEscapedCharField(
                        blank=True,
                        db_column="APELIDO",
                        max_length=512,
                        null=True,
                        verbose_name="Apelido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apelido",
                "verbose_name_plural": "Apelidos",
                "db_table": "R_UNIVERSIDADES_APELIDOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Continente",
            fields=[
                (
                    "id_continente",
                    models.AutoField(
                        db_column="ID_CONTINENTE", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nome_portugues",
                    rankings.models.UnicodeEscapedCharField(
                        db_column="NOME_CONTINENTE_PORTUGUES",
                        max_length=512,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    rankings.models.UnicodeEscapedCharField(
                        blank=True,
                        db_column="NOME_CONTINENTE_INGLES",
                        max_length=512,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
            ],
            options={
                "db_table": "R_CONTINENTES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GrupoDePilares",
            fields=[
                (
                    "id_grupo_pilares",
                    models.AutoField(
                        db_column="ID_GRUPO_PILARES", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nome_portugues",
                    rankings.models.UnicodeEscapedCharField(
                        db_column="NOME_GRUPO_PORTUGUES",
                        max_length=512,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    rankings.models.UnicodeEscapedCharField(
                        blank=True,
                        db_column="NOME_GRUPO_INGLES",
                        max_length=512,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de pilares",
                "verbose_name_plural": "Grupos de Pilares",
                "db_table": "R_PILARES_GRUPOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GrupoDeUniversidades",
            fields=[
                (
                    "id_grupo_universidades",
                    models.AutoField(
                        db_column="ID_GRUPO_UNIVERSIDADES",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome_portugues",
                    rankings.models.UnicodeEscapedCharField(
                        db_column="NOME_GRUPO_PORTUGUES",
                        max_length=512,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    rankings.models.UnicodeEscapedCharField(
                        blank=True,
                        db_column="NOME_GRUPO_INGLES",
                        max_length=512,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Universidades",
                "verbose_name_plural": "Grupos de Universidades",
                "db_table": "R_UNIVERSIDADES_GRUPOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GrupoGeopolitico",
            fields=[
                (
                    "id_grupo_geopolitico",
                    models.AutoField(
                        db_column="ID_GRUPO_GEOPOLITICO",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome_portugues",
                    rankings.models.UnicodeEscapedCharField(
                        db_column="NOME_GRUPO_PORTUGUES",
                        max_length=512,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    rankings.models.UnicodeEscapedCharField(
                        blank=True,
                        db_column="NOME_GRUPO_INGLES",
                        max_length=512,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
                (
                    "sigla",
                    rankings.models.UnicodeEscapedCharField(
                        blank=True,
                        db_column="SIGLA",
                        max_length=512,
                        null=True,
                        verbose_name="Sigla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo geopolítico",
                "verbose_name_plural": "Grupos Geopolíticos",
                "db_table": "R_GRUPOS_GEOPOLITICOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IES",
            fields=[
                (
                    "cod_ies",
                    models.AutoField(
                        db_column="COD_IES",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código IES",
                    ),
                ),
                (
                    "sigla_ies",
                    rankings.models.UnicodeEscapedCharField(
                        blank=True,
                        db_column="SIGLA_IES",
                        max_length=64,
                        null=True,
                        verbose_name="Sigla",
                    ),
                ),
                (
                    "nome_ies",
                    rankings.models.UnicodeEscapedCharField(
                        db_column="NOME_IES",
                        max_length=512,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instituição de Ensino Superior",
                "verbose_name_plural": "Instituições de Ensino Superior",
                "db_table": "IES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id_pais",
                    models.AutoField(
                        db_column="ID_PAIS",
                        primary_key=True,
                        serialize=False,
                        verbose_name="País",
                    ),
                ),
                (
                    "nome_portugues",
                    rankings.models.UnicodeEscapedCharField(
                        db_column="NOME_PAIS_PORTUGUES",
                        max_length=512,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    rankings.models.UnicodeEscapedCharField(
                        blank=True,
                        db_column="NOME_PAIS_INGLES",
                        max_length=512,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
            ],
            options={
                "verbose_name": "País",
                "verbose_name_plural": "Países",
                "db_table": "R_PAISES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PaisesParaGruposGeopoliticos",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "grupo_geopolitico_id",
                        "pais_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "R_PAISES_PARA_GRUPOS_GEOPOLITICOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pilar",
            fields=[
                (
                    "id_pilar",
                    models.AutoField(
                        db_column="ID_PILAR", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nome_portugues",
                    rankings.models.UnicodeEscapedCharField(
                        db_column="NOME_PILAR_PORTUGUES",
                        max_length=512,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    rankings.models.UnicodeEscapedCharField(
                        blank=True,
                        db_column="NOME_PILAR_INGLES",
                        max_length=512,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
                (
                    "descricao_portugues",
                    rankings.models.UnicodeEscapedCharField(
                        blank=True,
                        db_column="DESCRICAO_PILAR_PORTUGUES",
                        max_length=512,
                        null=True,
                        verbose_name="Descrição (PT-BR)",
                    ),
                ),
                (
                    "descricao_ingles",
                    rankings.models.UnicodeEscapedCharField(
                        blank=True,
                        db_column="DESCRICAO_PILAR_INGLES",
                        max_length=512,
                        null=True,
                        verbose_name="Descrição (EN-US)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pilar",
                "verbose_name_plural": "Pilares",
                "db_table": "R_PILARES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PilaresDetalhes",
            fields=[
                (
                    "id_pilar_detalhe",
                    models.AutoField(
                        db_column="ID_PILAR_DETALHE", primary_key=True, serialize=False
                    ),
                ),
                (
                    "ano_referencia",
                    models.SmallIntegerField(
                        blank=True, db_column="ANO_REFERENCIA", null=True
                    ),
                ),
                (
                    "identificador",
                    models.CharField(db_column="IDENTIFICADOR", max_length=64),
                ),
                (
                    "descricao_criterio_ingles",
                    models.CharField(
                        db_column="DESCRICAO_CRITERIO_INGLES", max_length=255
                    ),
                ),
                (
                    "descricao_criterio_portugues",
                    models.CharField(
                        blank=True,
                        db_column="DESCRICAO_CRITERIO_PORTUGUES",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("pontuacao", models.SmallIntegerField(db_column="PONTUACAO")),
                (
                    "pontuacao_maxima",
                    models.SmallIntegerField(
                        blank=True, db_column="PONTUACAO_MAXIMA", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalhes de um Pilar",
                "verbose_name_plural": "Detalhes de Pilares",
                "db_table": "R_PILARES_DETALHES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PilaresParaGrupos",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "pilar_id",
                        "grupo_pilares_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "R_PILARES_PARA_GRUPOS",
                "ordering": ["grupo_pilares", "pilar"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PilarValor",
            fields=[
                ("ano", models.IntegerField(db_column="ANO", verbose_name="Ano")),
                (
                    "valor_inicial",
                    models.FloatField(
                        blank=True,
                        db_column="VALOR_INICIAL",
                        null=True,
                        verbose_name="Valor Inicial",
                    ),
                ),
                (
                    "valor_final",
                    models.FloatField(
                        blank=True,
                        db_column="VALOR_FINAL",
                        null=True,
                        verbose_name="Valor Final",
                    ),
                ),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "apelido_universidade",
                        "pilar",
                        "ano",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor do Pilar",
                "verbose_name_plural": "Valores dos Pilares",
                "db_table": "R_PILARES_VALORES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id_ranking",
                    models.AutoField(
                        db_column="ID_RANKING", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nome",
                    rankings.models.UnicodeEscapedCharField(
                        db_column="NOME_RANKING",
                        max_length=512,
                        unique=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "ultima_atualizacao",
                    models.DateTimeField(
                        blank=True,
                        db_column="ULTIMA_ATUALIZACAO",
                        default=django.utils.timezone.now,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ranking",
                "verbose_name_plural": "Rankings",
                "db_table": "R_RANKINGS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoApelido",
            fields=[
                (
                    "id_tipo_apelido",
                    models.AutoField(
                        db_column="ID_TIPO_APELIDO", primary_key=True, serialize=False
                    ),
                ),
                (
                    "tipo_apelido",
                    rankings.models.UnicodeEscapedCharField(
                        db_column="TIPO_APELIDO",
                        max_length=512,
                        verbose_name="Tipo Apelido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo Apelido",
                "verbose_name_plural": "Tipos Apelidos",
                "db_table": "R_PAISES_APELIDOS_TIPOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UltimaCarga",
            fields=[
                (
                    "id_ultima_carga",
                    models.IntegerField(
                        blank=True,
                        db_column="ID_ULTIMA_CARGA",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome_tabela",
                    rankings.models.UnicodeEscapedCharField(
                        db_column="NOME_TABELA", max_length=128, unique=True
                    ),
                ),
                (
                    "dh_ultima_carga",
                    models.DateTimeField(
                        blank=True,
                        db_column="DH_ULTIMA_CARGA",
                        default=django.utils.timezone.now,
                        null=True,
                    ),
                ),
                (
                    "nome_ajustado",
                    rankings.models.UnicodeEscapedCharField(
                        blank=True, db_column="NOME_AJUSTADO", max_length=200, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Última Carga",
                "verbose_name_plural": "Últimas Cargas",
                "db_table": "ULTIMA_CARGA",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Universidade",
            fields=[
                (
                    "id_universidade",
                    models.AutoField(
                        db_column="ID_UNIVERSIDADE", primary_key=True, serialize=False
                    ),
                ),
                (
                    "cod_ies",
                    models.IntegerField(
                        blank=True,
                        db_column="COD_IES",
                        null=True,
                        verbose_name="Código IES",
                    ),
                ),
                (
                    "nome_portugues",
                    rankings.models.UnicodeEscapedCharField(
                        db_column="NOME_UNIVERSIDADE_PORTUGUES",
                        max_length=512,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
                (
                    "nome_ingles",
                    rankings.models.UnicodeEscapedCharField(
                        blank=True,
                        db_column="NOME_UNIVERSIDADE_INGLES",
                        max_length=512,
                        null=True,
                        verbose_name="Nome (EN-US)",
                    ),
                ),
                (
                    "sigla",
                    rankings.models.UnicodeEscapedCharField(
                        blank=True,
                        db_column="SIGLA",
                        max_length=512,
                        null=True,
                        verbose_name="Sigla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Universidade",
                "verbose_name_plural": "Universidades",
                "db_table": "R_UNIVERSIDADES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UniversidadesParaGrupos",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "universidade_id",
                        "grupo_universidades_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "R_UNIVERSIDADES_PARA_GRUPOS",
                "managed": False,
            },
        ),
    ]
