# Generated by Django 5.2.5 on 2025-08-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IES",
            fields=[
                (
                    "cod_ies",
                    models.AutoField(
                        db_column="COD_IES",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código IES",
                    ),
                ),
                (
                    "nome_ies",
                    models.CharField(
                        db_column="NOME_IES",
                        max_length=512,
                        verbose_name="Nome (PT-BR)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instituição de Ensino Superior",
                "verbose_name_plural": "Instituições de Ensino Superior",
                "db_table": "IES",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Metadado",
        ),
        migrations.DeleteModel(
            name="Metrica",
        ),
        migrations.DeleteModel(
            name="MetricasParaPilares",
        ),
        migrations.DeleteModel(
            name="MetricaValor",
        ),
        migrations.DeleteModel(
            name="TipoDeEntidade",
        ),
        migrations.DeleteModel(
            name="TipoDeMetadado",
        ),
    ]
