INSERT INTO R_PAISES(NOME_PAIS_PORTUGUES, NOME_PAIS_INGLES, ID_CONTINENTE) VALUES
    ('Afeganistão','Afghanistan',3),
    ('África do Sul','South Africa',1),
    ('Albânia','Albania',4),
    ('Alemanha','Germany',4),
    ('Andorra','Andorra',4),
    ('Angola','Angola',1),
    ('Antígua e Barbuda','Antigua and Barbuda',2),
    ('Arábia Saudita','Saudi Arabia',3),
    ('Argélia','Algeria',1),
    ('Argentina','Argentina',6),
    ('Armênia','Armenia',4),
    ('Austrália','Australia',5),
    ('Áustria','Austria',4),
    ('Azerbaijão','Azerbaijan',3),
    ('Bahamas','Bahamas',2),
    ('Bangladeche','Bangladesh',3),
    ('Barbados','Barbados',2),
    ('Barém','Bahrain',3),
    ('Bélgica','Belgium',4),
    ('Belize','Belize',2),
    ('Benim','Benin',1),
    ('Bielorrússia','Belarus',4),
    ('Bolívia','Bolivia',6),
    ('Bósnia e Herzegovina','Bosnia and Herzegovina',4),
    ('Botsuana','Botswana',1),
    ('Brasil','Brazil',6),
    ('Brunei','Brunei',3),
    ('Bulgária','Bulgaria',4),
    ('Burquina Faso','Burkina Faso',1),
    ('Burúndi','Burundi',1),
    ('Butão','Bhutan',3),
    ('Cabo Verde','Cape Verde',1),
    ('Camarões','Cameroon',1),
    ('Camboja','Cambodia',3),
    ('Canadá','Canada',7),
    ('Catar','Qatar',3),
    ('Cazaquistão','Kazakhstan',3),
    ('Chade','Chad',1),
    ('Chile','Chile',6),
    ('China','China',3),
    ('Chipre','Cyprus',4),
    ('Colômbia','Colombia',6),
    ('Comores','Comoros',1),
    ('Coreia do Norte','North Korea',3),
    ('Coreia do Sul','South Korea',3),
    ('Costa do Marfim','Ivory Coast',1),
    ('Costa Rica','Costa Rica',2),
    ('Croácia','Croatia',4),
    ('Cuba','Cuba',2),
    ('Dinamarca','Denmark',4),
    ('Dominica','Dominica',2),
    ('Egito','Egypt',1),
    ('Emirados Árabes Unidos','United Arab Emirates',3),
    ('Equador','Ecuador',6),
    ('Eritreia','Eritrea',1),
    ('Eslováquia','Slovakia',4),
    ('Eslovênia','Slovenia',4),
    ('Espanha','Spain',4),
    ('Estados Unidos','United States',7),
    ('Estônia','Estonia',4),
    ('Essuatíni','Eswatini',1),
    ('Etiópia','Ethiopia',1),
    ('Fiji','Fiji',5),
    ('Filipinas','Philippines',3),
    ('Finlândia','Finland',4),
    ('França','France',4),
    ('Gabão','Gabon',1),
    ('Gâmbia','Gambia',1),
    ('Gana','Ghana',1),
    ('Geórgia','Georgia',3),
    ('Granada','Grenada',2),
    ('Grécia','Greece',4),
    ('Guatemala','Guatemala',2),
    ('Guiana','Guyana',6),
    ('Guiné','Guinea',1),
    ('Guiné Equatorial','Equatorial Guinea',1),
    ('Guiné-Bissau','Guinea-Bissau',1),
    ('Haiti','Haiti',2),
    ('Honduras','Honduras',2),
    ('Hungria','Hungary',4),
    ('Iêmen','Yemen',3),
    ('Ilhas Marshall','Marshall Islands',5),
    ('Ilhas Salomão','Solomon Islands',5),
    ('Índia','India',3),
    ('Indonésia','Indonesia',3),
    ('Irã','Iran',3),
    ('Iraque','Iraq',3),
    ('Irlanda','Ireland',4),
    ('Islândia','Iceland',4),
    ('Israel','Israel',3),
    ('Itália','Italy',4),
    ('Jamaica','Jamaica',2),
    ('Japão','Japan',3),
    ('Jibuti','Djibouti',1),
    ('Jordânia','Jordan',3),
    ('Kosovo','Kosovo',4),
    ('Kuwait','Kuwait',3),
    ('Laos','Laos',5),
    ('Lesoto','Lesotho',1),
    ('Letônia','Latvia',4),
    ('Líbano','Lebanon',3),
    ('Libéria','Liberia',1),
    ('Líbia','Libya',1),
    ('Liechtenstein','Liechtenstein',4),
    ('Lituânia','Lithuania',4),
    ('Luxemburgo','Luxembourg',4),
    ('Macedônia do Norte','North Macedonia',4),
    ('Madagascar','Madagascar',1),
    ('Malásia','Malaysia',3),
    ('Malávi','Malawi',1),
    ('Maldivas','Maldives',3),
    ('Mali','Mali',1),
    ('Malta','Malta',4),
    ('Marrocos','Morocco',1),
    ('Maurícia','Mauritius',1),
    ('Mauritânia','Mauritania',1),
    ('México','Mexico',7),
    ('Micronésia','Micronesia',5),
    ('Moçambique','Mozambique',1),
    ('Moldávia','Moldova',4),
    ('Mônaco','Monaco',4),
    ('Mongólia','Mongolia',3),
    ('Montenegro','Montenegro',4),
    ('Myanmar','Myanmar',3),
    ('Namíbia','Namibia',1),
    ('Nauru','Nauru',5),
    ('Nepal','Nepal',3),
    ('Nicarágua','Nicaragua',2),
    ('Níger','Niger',1),
    ('Nigéria','Nigeria',1),
    ('Noruega','Norway',4),
    ('Nova Zelândia','New Zealand',5),
    ('Omã','Oman',3),
    ('Países Baixos','Netherlands',5),
    ('Palau','Palau',5),
    ('Panamá','Panama',2),
    ('Papua-Nova Guiné','Papua New Guinea',5),
    ('Paquistão','Pakistan',3),
    ('Paraguai','Paraguay',6),
    ('Peru','Peru',6),
    ('Polônia','Poland',4),
    ('Portugal','Portugal',4),
    ('Quênia','Kenya',1),
    ('Quirguistão','Kyrgyzstan',3),
    ('Quiribáti','Kiribati',5),
    ('Reino Unido','United Kingdom',4),
    ('República Centro-Africana','Central African Republic',1),
    ('República Checa','Czech Republic',4),
    ('República Democrática do Congo','Democratic Republic of the Congo',1),
    ('República do Congo','Republic of the Congo',1),
    ('República Dominicana','Dominican Republic',2),
    ('Romênia','Romania',4),
    ('Ruanda','Rwanda',1),
    ('Rússia','Russia',4),
    ('Salisbúria do Norte','North Salisbury',1),
    ('Samoa','Samoa',5),
    ('Santa Lúcia','Saint Lucia',2),
    ('São Cristóvão e Neves','Saint Kitts and Nevis',2),
    ('San Marino','San Marino',4),
    ('São Tomé e Príncipe','São Tomé and Príncipe',1),
    ('São Vicente e Granadinas','Saint Vincent and the Grenadines',2),
    ('Seicheles','Seychelles',1),
    ('Senegal','Senegal',1),
    ('Serra Leoa','Sierra Leone',4),
    ('Sérvia','Serbia',4),
    ('Singapura','Singapore',3),
    ('Síria','Syria',3),
    ('Somália','Somalia',3),
    ('Sri Lanka','Sri Lanka',3),
    ('Sudão','Sudan',1),
    ('Sudão do Sul','South Sudan',1),
    ('Suécia','Sweden',4),
    ('Suíça','Switzerland',4),
    ('Suriname','Suriname',6),
    ('Tailândia','Thailand',3),
    ('Taiwan','Taiwan',3),
    ('Tajiquistão','Tajikistan',3),
    ('Tanzânia','Tanzania',1),
    ('Timor-Leste','Timor-Leste',3),
    ('Togo','Togo',1),
    ('Tonga','Tonga',5),
    ('Trinidade e Tobago','Trinidad and Tobago',2),
    ('Tunísia','Tunisia',1),
    ('Turcomenistão','Turkmenistan',3),
    ('Turquia','Turkey',3),
    ('Tuvalu','Tuvalu',5),
    ('Ucrânia','Ukraine',4),
    ('Uganda','Uganda',1),
    ('Uruguai','Uruguay',6),
    ('Uzbequistão','Uzbekistan',3),
    ('Vanuatu','Vanuatu',5),
    ('Vaticano','Vatican',4),
    ('Venezuela','Venezuela',6),
    ('Vietnã','Vietnam',3),
    ('Zâmbia','Zambia',1),
    ('Zimbábue','Zimbabwe',1),
    ('Palestina','Palestine',3),
    ('El Salvador','El Salvador', 2);