INSERT INTO R_GRUPOS_GEOPOLITICOS(NOME_GRUPO_PORTUGUES, NOME_GRUPO_INGLES) VALUES ('BRICS', 'BRICS');
INSERT INTO R_GRUPOS_GEOPOLITICOS(NOME_GRUPO_PORTUGUES, NOME_GRUPO_INGLES) VALUES ('Mercosul', 'Mercosur');
INSERT INTO R_GRUPOS_GEOPOLITICOS(NOME_GRUPO_PORTUGUES, NOME_GRUPO_INGLES) VALUES ('América Latina', 'Latin America');