-- BRICS

INSERT INTO R_PAISES_PARA_GRUPOS_GEOPOLITICOS(ID_GRUPO_GEOPOLITICO, ID_PAIS) VALUES (1, 2);  -- áfrica do sul
INSERT INTO R_PAISES_PARA_GRUPOS_GEOPOLITICOS(ID_GRUPO_GEOPOLITICO, ID_PAIS) VALUES (1, 26);  -- brasil
INSERT INTO R_PAISES_PARA_GRUPOS_GEOPOLITICOS(ID_GRUPO_GEOPOLITICO, ID_PAIS) VALUES (1, 40);  -- china
INSERT INTO R_PAISES_PARA_GRUPOS_GEOPOLITICOS(ID_GRUPO_GEOPOLITICO, ID_PAIS) VALUES (1, 84);  -- índia
INSERT INTO R_PAISES_PARA_GRUPOS_GEOPOLITICOS(ID_GRUPO_GEOPOLITICO, ID_PAIS) VALUES (1, 154); -- rússia

-- -- MERCOSUL

INSERT INTO R_PAISES_PARA_GRUPOS_GEOPOLITICOS(ID_GRUPO_GEOPOLITICO, ID_PAIS) VALUES (2, 10);  -- argentina
INSERT INTO R_PAISES_PARA_GRUPOS_GEOPOLITICOS(ID_GRUPO_GEOPOLITICO, ID_PAIS) VALUES (2, 26);  -- brasil
INSERT INTO R_PAISES_PARA_GRUPOS_GEOPOLITICOS(ID_GRUPO_GEOPOLITICO, ID_PAIS) VALUES (2, 139);  -- paraguai
INSERT INTO R_PAISES_PARA_GRUPOS_GEOPOLITICOS(ID_GRUPO_GEOPOLITICO, ID_PAIS) VALUES (2, 189);  -- uruguai
INSERT INTO R_PAISES_PARA_GRUPOS_GEOPOLITICOS(ID_GRUPO_GEOPOLITICO, ID_PAIS) VALUES (2, 193);  -- venezuela

-- AMÉRICA LATINA

INSERT INTO R_PAISES_PARA_GRUPOS_GEOPOLITICOS (ID_GRUPO_GEOPOLITICO, ID_PAIS)
SELECT 3, ID_PAIS FROM (
    select ID_PAIS
    from R_PAISES
    WHERE ID_CONTINENTE IN (
        SELECT ID_CONTINENTE FROM R_CONTINENTES WHERE lower(NOME_CONTINENTE_PORTUGUES) IN (
            lower('América do Sul'), lower('América Central e Caribe')
        )
    )
    UNION
        SELECT ID_PAIS
        FROM R_PAISES WHERE LOWER(NOME_PAIS_PORTUGUES) = lower('México')
);
DELETE FROM R_PAISES_PARA_GRUPOS_GEOPOLITICOS
WHERE ID_PAIS IN (
    SELECT ID_PAIS
    FROM R_PAISES
    WHERE lower(NOME_PAIS_PORTUGUES) IN (
        lower('Guiana'), lower('Suriname'), lower('Belize'), lower('Jamaica'), lower('Trinidade e Tobago')
    )
);