-- tabelas inseridas pelo django
DROP TABLE auth_group_permissions;
DROP TABLE auth_user_groups;
DROP TABLE auth_group;
DROP TABLE auth_user_user_permissions;
DROP TABLE auth_permission;
DROP TABLE django_admin_log;
DROP TABLE auth_user;
DROP TABLE django_content_type;
DROP TABLE django_migrations;
DROP TABLE django_session;

-- tabelas do banco de dados de rankings
DROP TABLE R_FORMULARIOS;
DROP TABLE R_METADADOS;
DROP TABLE R_METRICAS_PARA_PILARES;
DROP TABLE R_METRICAS_VALORES;
DROP TABLE R_METRICAS;
DROP TABLE R_PAISES_PARA_GRUPOS_GEOPOLITICOS;
DROP TABLE R_GRUPOS_GEOPOLITICOS;
DROP TABLE R_PILARES_PARA_GRUPOS;
DROP TABLE R_PILARES_GRUPOS;
DROP TABLE R_PILARES_VALORES;
DROP TABLE R_PILARES;
DROP TABLE R_RANKINGS;
DROP TABLE R_TIPOS_ENTIDADES;
DROP TABLE R_TIPOS_METADADOS;
DROP TABLE R_UNIVERSIDADES_APELIDOS;
DROP TABLE R_UNIVERSIDADES_PARA_GRUPOS;
DROP TABLE R_UNIVERSIDADES;
DROP TABLE R_PAISES_APELIDOS;
DROP TABLE R_PAISES;
DROP TABLE R_CONTINENTES;
DROP TABLE R_PAISES_APELIDOS_TIPOS;
DROP TABLE R_UNIVERSIDADES_GRUPOS;

DROP VIEW R_V_RANKINGS_DIMENSAO;
DROP VIEW R_V_UNIVERSIDADES_DIMENSAO;
DROP VIEW R_V_PILARES_VALORES_FATO;